export type Country = {
  value: string;
  label: string;
};

export const COUNTRIES: Country[] = [
  { value: "AF", label: "Afeganistão" },
  { value: "ZA", label: "África do Sul" },
  { value: "DE", label: "Alemanha" },
  { value: "SA", label: "Arábia Saudita" },
  { value: "AR", label: "Argentina" },
  { value: "AU", label: "Austrália" },
  { value: "AT", label: "Áustria" },
  { value: "BE", label: "Bélgica" },
  { value: "BR", label: "Brasil" },
  { value: "CA", label: "Canadá" },
  { value: "CL", label: "Chile" },
  { value: "CN", label: "China" },
  { value: "CO", label: "Colômbia" },
  { value: "KR", label: "Coreia do Sul" },
  { value: "DK", label: "Dinamarca" },
  { value: "EG", label: "Egito" },
  { value: "AE", label: "Emirados Árabes Unidos" },
  { value: "ES", label: "Espanha" },
  { value: "US", label: "Estados Unidos" },
  { value: "PH", label: "Filipinas" },
  { value: "FI", label: "Finlândia" },
  { value: "FR", label: "França" },
  { value: "GR", label: "Grécia" },
  { value: "NL", label: "Holanda" },
  { value: "HK", label: "Hong Kong" },
  { value: "HU", label: "Hungria" },
  { value: "IN", label: "Índia" },
  { value: "ID", label: "Indonésia" },
  { value: "IE", label: "Irlanda" },
  { value: "IT", label: "Itália" },
  { value: "JP", label: "Japão" },
  { value: "MY", label: "Malásia" },
  { value: "MX", label: "México" },
  { value: "NO", label: "Noruega" },
  { value: "NZ", label: "Nova Zelândia" },
  { value: "PE", label: "Peru" },
  { value: "PL", label: "Polônia" },
  { value: "PT", label: "Portugal" },
  { value: "GB", label: "Reino Unido" },
  { value: "CZ", label: "República Tcheca" },
  { value: "RO", label: "Romênia" },
  { value: "RU", label: "Rússia" },
  { value: "SG", label: "Singapura" },
  { value: "SE", label: "Suécia" },
  { value: "CH", label: "Suíça" },
  { value: "TH", label: "Tailândia" },
  { value: "TW", label: "Taiwan" },
  { value: "TR", label: "Turquia" },
  { value: "UA", label: "Ucrânia" },
  { value: "VN", label: "Vietnã" },
];
